version: '3'

services:
  happyfoody-postgres:
    container_name: happyfoody-postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: admindb
    ports:
      - 5432:5432